Add Input for KPI calcualtions
jmandt/stock-market-extremes-cloud-functions pull request #1
Opened 2020-03-14 19:32 UTC by JuergenSoeren

Includes first mapping on financial modeling prep api

2020-03-14 19:32 UTC, JuergenSoeren commented
Guckt mal ob das verständlich ist..

2020-03-15 16:19 UTC, arneous commented on README.md
> +|Summe Eigenkapital   | Bilanz (Passiva)  | Balance Sheet > Total shareholders equity  |   |   |
Also found this here: https://financialmodelingprep.com/api/v3/financials/balance-sheet-statement/AAPL

2020-03-15 18:20 UTC, arneous reviewed
Updated list

2020-03-15 18:20 UTC, arneous commented on README.md
> +|Ergebnis je Aktie verwässert   | "Wertpapierdaten"  |   |   | Kann man auch berechnen  |
Is das nicht "EPS Diluted" in https://financialmodelingprep.com/api/v3/financials/income-statement/AAPL ?

2020-03-15 18:20 UTC, arneous commented on README.md
> +|Umsatz je Aktie   | "Wertpapierdaten"  |   |   | Kann man auch berechnen |
Vielleicht "Revenue per Share" aus https://financialmodelingprep.com/api/v3/company-key-metrics/AAPL

2020-03-15 18:25 UTC, arneous commented
I did a review!

2020-03-15 18:27 UTC, arneous requested changes
Lets also check other fields in
https://financialmodelingprep.com/api/v3/company-key-metrics/AAPL

2020-03-15 18:40 UTC, merged